---
title: "Chapter 1 - Three tools for Golem Engineering"
output: html_notebook
---

Instead of choosing among various black-box tools for testing null hypotheses, we whould learn to build and analyze multiple non-null modles of natural phenomena.

1. *Bayesian data analysis*

    In modest terms, Bayesian inference is no more than counting the numbers of ways things can happen, according to our assumptions. Things that can happen more ways are     more plausible.


2. *Multilevel models*
    a. Adjust estimates for repeat sampling: More than one observation per subject.
    b. Adjust estimates for imbalanced sampling: When some subjects have more observations than others.
    c. To study variation: Especially variation between subjects with the observations.
    d. Avoid averaging.
    

    The author argues that multilevel models should be the default form of regression.


3. *Model comparison using information criteria*

    Information criteria aims to compare models based upon future predictive accuracy. 
    
    a. They help researchers prevent overfitting
    b. They allow for the comparison of multiple non-null models to the same data.


